#ifndef VIETTELSDK_COMMAND_LIST_H_
#define VIETTELSDK_COMMAND_LIST_H_

#ifndef POWER_OFF
#define POWER_OFF "AT+CFUN"
#endif

#ifndef EPS_NETWORK_REGISTRATION_STATUS
#define EPS_NETWORK_REGISTRATION_STATUS "AT+CEREG"
#endif

#ifndef SHOW_ICCID
#define SHOW_ICCID "AT+QCCID"
#endif

#ifndef SIGNAL_QUALITY_REPORT
#define SIGNAL_QUALITY_REPORT "AT+CSQ"
#endif

#ifndef COMMAND_ECHO_MODE
#define COMMAND_ECHO_MODE "ATE"
#endif

#ifndef REQUEST_IMEI
#define REQUEST_IMEI "AT+CGSN"
#endif

#ifndef REQUEST_TA_REVISION_ID
#define REQUEST_TA_REVISION_ID "AT+CGMR"
#endif

#ifndef OPERATOR_SELECTION
#define OPERATOR_SELECTION "AT+COPS"
#endif

#ifndef REPORT_MOBILE_EQUIPMENT_ERROR
#define REPORT_MOBILE_EQUIPMENT_ERROR "AT+CMEE"
#endif

#ifndef DISPLAY_PRODUCT_ID
#define DISPLAY_PRODUCT_ID "ATI"
#endif

#ifndef REQUEST_MANUFACTURER_ID
#define REQUEST_MANUFACTURER_ID "AT+CGMI"
#endif

#ifndef REQUEST_MODEL_ID
#define REQUEST_MODEL_ID "AT+CGMM"
#endif

#ifndef REQUEST_INTERNATIONAL_MOBILE_SUBSCRIBER_IDENTITY
#define REQUEST_INTERNATIONAL_MOBILE_SUBSCRIBER_IDENTITY "AT+CIMI"
#endif

#ifndef GET_AND_SET_MOBILE_OPERATION_BAND
#define GET_AND_SET_MOBILE_OPERATION_BAND "AT+QBAND"
#endif

#define SET_DEFAULT_PSD_CONNECTION "AT+QCGDEFCONT"
#ifndef SET_DEFAULT_PSD_CONNECTION
#endif

#ifndef REPORT_NETWORK_STATE
#define REPORT_NETWORK_STATE "AT+QENG"
#endif

#ifndef PREFERRED_OPERATOR_LIST
#define PREFERRED_OPERATOR_LIST "AT+CPOL"
#endif

#ifndef CONFIG_WAKEUP_INDICATION_AT_CMD
#define CONFIG_WAKEUP_INDICATION_AT_CMD "AT+QNBIOTEVENT"
#endif

#ifndef SET_BAUDRATE_AT_CMD
#define SET_BAUDRATE_AT_CMD "AT+IPR"
#endif

#ifndef ENABLE_RELEASE_ASSISTANCE_INDICATION_AT_CMD
#define ENABLE_RELEASE_ASSISTANCE_INDICATION_AT_CMD "AT+CNBIOTRAI"
#endif

#ifndef CONFIG_CIOT_OPTIMIZATION_AT_CMD
#define CONFIG_CIOT_OPTIMIZATION_AT_CMD "AT+CCIOTOPT"
#endif

#ifndef CONFIG_SLOW_CLOCK_AT_CMD
#define CONFIG_SLOW_CLOCK_AT_CMD "AT+QSCLK"
#endif

#ifndef CONFIG_SOCKET_RETENTION_AT_CMD
#define CONFIG_SOCKET_RETENTION_AT_CMD "AT+RETENTION"
#endif

#ifndef PSM_AT_CMD
#define PSM_AT_CMD "AT+CPSMS"
#endif

#ifndef CONFIG_EDRX_AT_CMD
#define CONFIG_EDRX_AT_CMD "AT*MEDRXCFG"
#endif

#ifndef QUERY_EDRX_AT_CMD
#define QUERY_EDRX_AT_CMD "AT+CEDRXRDP"
#endif

#ifndef ENTER_PIN
#define ENTER_PIN "AT+CPIN"
#endif

#ifndef PHONE_FUCNTIONALITY
#define PHONE_FUCNTIONALITY "AT+CFUN"
#endif

#ifndef READ_DYNAMIC_PARAM_PDP_CONTEXT
#define READ_DYNAMIC_PARAM_PDP_CONTEXT "AT+CGDCONT"
#endif

#ifndef AUTO_TIME_UPDATE
#define AUTO_TIME_UPDATE "AT+CTZU"
#endif

#ifndef ENABLE_LOCAL_TIMESTAMP
#define ENABLE_LOCAL_TIMESTAMP "AT+CLTS"
#endif

#ifndef GET_CLOCK
#define GET_CLOCK "AT+CCLK"
#endif

#ifndef CHECK_ACTIVE_PDP_CONTEXT
#define CHECK_ACTIVE_PDP_CONTEXT "AT+CGACT"
#endif

#ifndef CONTROL_THE_DATA_OUTPUT_FORMAT
#define CONTROL_THE_DATA_OUTPUT_FORMAT "AT+CREVHEX"
#endif

/* MQTT */
#ifndef CREATE_NEW_MQTT_AT_CMD
#define CREATE_NEW_MQTT_AT_CMD "AT+CMQNEW"
#endif

#ifndef SEND_NEW_MQTT_CONNECTION_PACKET_AT_CMD
#define SEND_NEW_MQTT_CONNECTION_PACKET_AT_CMD "AT+CMQCON"
#endif

#ifndef SEND_MQTT_PUBLISH_PACKET_AT_CMD
#define SEND_MQTT_PUBLISH_PACKET_AT_CMD "AT+CMQPUB"
#endif

#ifndef DISCONNECT_MQTT_AT_CMD
#define DISCONNECT_MQTT_AT_CMD "AT+CMQDISCON"
#endif

#ifndef NEW_MQTT
#define NEW_MQTT "AT+CMQNEW"
#endif

#ifndef SEND_MQTT_CONNECT
#define SEND_MQTT_CONNECT "AT+CMQCON"
#endif

#ifndef SEND_MQTT_PUB
#define SEND_MQTT_PUB "AT+CMQPUB"
#endif

#ifndef SEND_MQTT_SUB
#define SEND_MQTT_SUB "AT+CMQSUB"
#endif

#ifndef SEND_MQTT_UNSUB
#define SEND_MQTT_UNSUB "AT+CMQUNSUB"
#endif

#ifndef MQTT_DISCONNECT
#define MQTT_DISCONNECT "AT+CMQDISCON"
#endif

#ifndef CREATE_COAP_CONTEXT
#define CREATE_COAP_CONTEXT "AT+QCOAPOPEN"
#endif

#ifndef CONFIG_COAP_MESSAGE_OPTIONS
#define CONFIG_COAP_MESSAGE_OPTIONS "AT+QCOAPOPTION"
#endif

#ifndef CONFIG_COAP_HEADER
#define CONFIG_COAP_HEADER "AT+QCOAPHEAD"
#endif

#ifndef COAP_DISCONNECT
#define COAP_DISCONNECT "AT+QCOAPCLOSE"
#endif

#ifndef SEND_COAP_MESSAGE
#define SEND_COAP_MESSAGE "AT+QCOAPSEND"
#endif

#ifndef READVOLTAGE
#define READVOLTAGE "AT+CBC"
#endif
#endif /* VIETTELSDK_COMMAND_LIST_H_ */
